// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hohfvjzagukucseffpmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvaGZ2anphZ3VrdWNzZWZmcG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzI0NTksImV4cCI6MjA2MjY0ODQ1OX0.vvu4ZjMG6UWwIZOlsIz0Bpv8C0uAAsRyHFgL46Y1Na4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);